networks:
  general_network:
    driver: bridge

services:
  redpanda-kafka:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda-kafka:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-kafka:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda-kafka:33145
      - --advertise-rpc-addr redpanda-kafka:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.12
    container_name: redpanda-kafka
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - general_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
  console-kafka:
    container_name: redpanda-console-kafka
    image: docker.redpanda.com/redpandadata/console:v2.4.6
    networks:
      - general_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-kafka:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-kafka:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-kafka:9644"]
    ports:
      - 8084:8080
    depends_on:
      - redpanda-kafka

secrets:
  npm:
    file: ${HOME}/.npmrc